name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # was: actions/checkout@v4
      
      - name: Setup test environment
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck
      
      - name: Run all tests
        run: |
          chmod +x tests/run-all-tests.sh
          ./tests/run-all-tests.sh

      - name: Verify script is executable
        run: |
          ./gh-refme --version
